### Get all artists
GET /api/publisher HTTP/1.1
Host: localhost:8080
Content-Type: application/json

### Get artist by id
GET /api/publisher/10 HTTP/1.1
Host: localhost:8080
Content-Type: application/json